---
# tasks file for roles/webserver
- name: Install Apache
  yum:
    name: httpd
    state: present

- name: Starting Apache
  service:
    name: httpd
    state: started
    enabled: true

- name: Copy files
  copy: src=devops.png dest=/var/www/html/

- name: Generate Template
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  notify:
    - Restarting Apache